---
swagger: "2.0"
info:
  description: Ping Demonstration
  title: "PingGateway"
  version: "1"

basePath: "/v01"

schemes:
- "http"
- "https"

paths:
  /:
    get:
      consumes:
      - "application/json"
      produces:
      - "text/html"

      responses:
        200:
          description: "200 response"
          headers:
            Content-Type:
              type: "string"

      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Content-Type: "'text/html'"
            responseTemplates:
              text/html: "<html>\n    <body>\n        <h1>responseTemplate</h1>\n    </body>\n </html>"
        requestTemplates:
          application/json: "{\"statusCode\": 200}"
        passthroughBehavior: "when_no_match"
        type: "mock"

  /ping:
    post:
      consumes:
      - "application/json"
      produces:
      - "application/json"

      parameters:
      - in: "body"
        name: "PingRequestV1"
        required: true
        schema:
          $ref: "#/definitions/PingRequestV1"

      responses:
        201:
          description: "201 response"
          schema:
            $ref: "#/definitions/PingResponseV1"
          headers:
            Access-Control-Allow-Origin:
              type: "string"

      x-amazon-apigateway-request-validator: "ping validator"

      x-amazon-apigateway-integration:
        uri: "${ping_lambda_arn}"

        responses:
          default:
            statusCode: "201"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
            responseTemplates:
              application/json: "#set($inputRoot = $input.path('$'))\n \
                {\n  \"preamble\" : {\n \
                \"transactionUuid\" : \"$inputRoot.transactionUuid\",\n  \
                \"messageVersion\" : 1,\n \
                \"messageType\" : \"PING\"\n  },\n \
                \"pingState\" : $inputRoot.pingState\n}\n"

        requestTemplates:
          application/json: "#set($inputRoot = $input.path('$'))\n \
                {\n  \"preamble\" : {\n \
                       \"transactionUuid\" : \"$inputRoot.preamble.transactionUuid\",\n  \
                       \"messageVersion\" : 1,\n \
                       \"messageVerb\" : \"POST\",\n \
                       \"messageType\" : \"PING\"\n  },\n \
                \"pingState\" : $inputRoot.pingState\n}"

        passthroughBehavior: "never"
        httpMethod: "POST"
        type: "aws"

  /ping/{transactionUuid}:
    get:
      produces:
      - "application/json"

      parameters:
      - name: "transactionUuid"
        in: "path"
        required: true
        type: "string"

      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/PingResponseV1"
          headers:
            Access-Control-Allow-Origin:
              type: "string"

      x-amazon-apigateway-integration:
        uri: "${ping_lambda_arn}"

        responses:
          default:
            statusCode: "200"

            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"

        requestTemplates:
          application/json: "#set($inputRoot = $input.path('$'))\n \
            {\n  \"preamble\" : {\n \
              \"transactionUuid\" : \"$inputRoot.transactionUuid\",\n  \
              \"messageVersion\" : 1,\n \
              \"messageType\" : \"PING\"\n  },\n \
              \"pingState\" : true\n}\n"

        passthroughBehavior: "never"
        httpMethod: "POST"
        type: "aws"

definitions:
  PingResponseV1:
    type: "object"
    required:
    - "pingState"
    - "preamble"
    properties:
      preamble:
        type: "object"
        properties:
          transactionUuid:
            type: "string"
            format: "uuid"
            description: "client generated transaction UUID"
          messageVersion:
            type: "integer"
            description: "message schema version"
          messageType:
            type: "string"
            description: "message type, always PING"
        required:
        - "transactionUuid"
      pingState:
        type: "boolean"
    title: "PingResponseV1"

  PingRequestV1:
    type: "object"
    required:
    - "pingState"
    - "preamble"
    properties:
      preamble:
        type: "object"
        properties:
          transactionUuid:
            type: "string"
            format: "uuid"
            description: "client generated transaction UUID"
          messageVersion:
            type: "integer"
            description: "defined by URL"
          messageType:
            type: "string"
            description: "defined by URL"
        required:
        - "transactionUuid"
      pingState:
        type: "boolean"
    title: "PingRequestV1"

x-amazon-apigateway-request-validators:
  ping validator:
    validateRequestParameters: true
    validateRequestBody: true
